POST http://localhost:3080/auth/signup
Content-Type: application/json

{
    "username": "Robs2",
    "email": "robs2@gmail.com",
    "password": "1234qwQW!"
}

###
POST http://localhost:3080/auth/login
Content-Type: application/json

{
    "username": "Robs2",
    "email": "robs2@gmail.com",
    "password": "1234qwQW!"
}

###
POST http://localhost:3080/auth/forgot-password
Content-Type: application/json

{
    "email": "vincentcornelius489@gmail.com"
}